config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
             :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'users/registrations',
                 :sessions=>'users/sessions'
             }

  devise_for :centers,
             :path=>'recruteur',
             :path_names=>{:sign_in=>'login', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'centers/registrations',
                 :sessions=>'centers/sessions'
             }

  devise_for :rhagents,
             :path=>'rhagents',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'rhagents/registrations',
                 :sessions=>'rhagents/sessions'
             }

  resources :users do
    get :matching_offers
    patch :approve
  end
  resources :offers do
    patch :mark_as_filled
  end
  resources :centers
  resources :rhagents
  resources :availabilities
  resources :circonscriptions
  resources :schools
  resources :slots
  resources :diplomas

  # root page of the application

  root 'pages#home'
  get '/animateurs' => 'users#manage'
end

app/models/center.rb
class Center < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,  :confirmable, :recoverable, :rememberable, :trackable, :validatable

  has_many :offers, dependent: :destroy
  has_many :schools

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence:true, length: {maximum: 50}
  validates :last_name, presence:true, length: {maximum: 50}
  validates :phone_number, presence: true, length: {is: 10}, uniqueness: true, numericality: {only_integer: true}
  validates :circonscription, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    end
  end

end

app/controllers/centers/confirmations_controller.rb
class Centers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/centers/omniauth_callbacks_controller.rb
class Centers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/centers/passwords_controller.rb
class Centers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/centers/registrations_controller.rb
class Centers::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, only: [:edit, :update, :destroy]
  before_action :configure_sign_up_params, only: [:create, :update]
  # before_action :configure_account_update_params, only: [:update]

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end


  protected
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :phone_number, :password, :password_confirmation, :circonscription])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :circonscription])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/centers/sessions_controller.rb
class Centers::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/centers/unlocks_controller.rb
class Centers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  # Center = REV User
  before_action :set_center, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @centers = Center.all.order('created_at DESC')
  end

  def show
  end

  def edit
  end

  def update
    if @center.update(center_params)
      redirect_to centers_path(@center), notice: "L'élément a été modifié avec succès"
    else
      render :edit
    end
  end

  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: "L'élément a bien été supprimé" }
      format.json { head :no_content }
    end
  end

  private
  def set_center
    @center = Center.find(params[:id])
  end

  def center_params
    params.require(:center).permit(:first_name, :last_name, :email, :circonscription, :phone_number, :approved)
  end

end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/edit.html.erb
<div class="container">
  <div class="col-md-8 col-sm-12 col-md-offset-2 form-flex form-panel_wrapper">
    <%= form_for @center do |f| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="form-heading-title">Modifier le profil du REV</div>
          </div>
          <div class="panel-body">
            <div class="form-group required">
              <%= f.label :email, 'Email', class: 'control-label'%>
              <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Adresse e-mail' %>
            </div>
            <div class="form-group required">
              <%= f.label :first_name, 'Prénom', class: 'control-label'%>
              <%= f.text_field :first_name, class: 'form-control', placeholder: 'Prénom' %>
            </div>
            <div class="form-group required">
              <%= f.label :last_name, 'Nom', class: 'control-label'%>
              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Nom' %>
            </div>
            <div class="form-group required">
              <%= f.label :phone_number, 'Numéro de tél.', class: 'control-label'%>
              <%= f.text_field :phone_number, class: 'form-control', placeholder: 'Numéro de téléphone' %>
            </div>
            <div class="form-group required">
              <%= f.label :circonscription, 'Circonscription', class: 'control-label' %>
              <%= f.collection_select :circonscription, Circonscription.all, :name, :name, {}, { class: 'form-control' } %>
            </div>
          </div>
        </div>
        <%= f.submit t('.sign_up', default: 'Modifier le profil'), class: 'btn btn-edit-form' %>
    <% end %>
  </div>
</div>

app/views/centers/index.html.erb
<div class="container">
  <div class="col-md-12">
    <h2>Tous les REV (<%= @centers.count %>)</h2>
      <% @centers.each do |center| %>
        <div class="col-md-12" style="border: 1px solid lightslategray; padding: 10px; margin-bottom: 15px;">
            <div class="col-md-3">
              <strong><%= center.first_name %> <%= center.last_name %></strong><br />
              <%= center.email %> <br />
              <%= center.phone_number %> <br />
              <%= center.circonscription %><br />
            </div>
            <div class="col-md-3">
              Ecoles:
              <% center.schools.each do |school| %>
              <div><%= school.name.titleize %></div>
              <% end %>
            </div>
            <div class="col-md-6">Offres:
              <% center.offers.each do |offer| %>
                  <div><%= l offer.date.to_date, format: '%A' %> <%= l offer.date.to_date, format: :long %></div>
              <% end %>
            </div>
          <div class="col-md-12">
            <%= link_to 'Modifier', edit_center_path(center) %>
            <%= link_to 'Supprimer', center, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/centers/show.html.erb
<div class="container">
  <div class="col-md-6">
    <h2>Mes infos</h2>
    <div><strong><%= @center.first_name %> <%= @center.last_name %></strong></div>
    <div><%= @center.email %></div>
    <div><%= @center.phone_number %></div>
    <div><%= @center.circonscription %></div>
    <%= link_to 'Modifier', edit_center_registration_path(@center) %>
  </div>
  <div class="col-md-6">
    <h2>Mes écoles</h2>

    <% @center.schools.each do |school| %>
      <%= link_to school_path(school) do %>
        <div><strong><%= school.name %></strong></div>
      <% end %>
      <div><%= school.address %></div>
      <br />
    <% end %>
  </div>
  <div class="col-md-12">
    <h2>Mes offres</h2>

    <table class="center-offers-wrapper table table-striped table-hover">
      <thead>
      <tr>
        <th>Ecole</th>
        <th>Date</th>
        <th>Services</th>
        <th>Diplômes requis</th>
        <th>Statut</th>
        <th>Actions</th>
      </tr>
      </thead>
      <% @center.offers.order("date desc").each do |offer| %>
          <tr>
            <td><%= offer.school.name %></td>
            <td><%= l offer.date.to_date, format: '%A' %> <%= l offer.date.to_date, format: :long %></td>
            <td>
              <% offer.slots.each do |slot|  %>
                  <div>
                  <%= slot.name %>
                  </div>
              <% end %>
            </td>
            <td>
              <% offer.diplomas.each do |diploma|  %>
                  <div>
                    <%= diploma.name %>
                  </div>
              <% end %>
            </td>
            <td>
              <% if offer.filled %>
                  <div class="badge success center">
                    OFFRE POURVUE
                  </div>
              <% end %>
            </td>
            <td>
              <% if offer.filled %>
              <%= link_to 'Remettre en ligne', offer_mark_as_filled_path(offer, filled: false), class: "btn btn-small btn-violet", method: :patch %>
              <% else %>
                  <%= link_to 'Marquer commme pourvue', offer_mark_as_filled_path(offer, filled: true), class: "btn btn-small btn-turquoise", method: :patch %>
              <% end %>
              <br/>
            <%= link_to 'Supprimer', offer, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>