config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
             :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'users/registrations',
                 :sessions=>'users/sessions'
             }

  devise_for :centers,
             :path=>'recruteur',
             :path_names=>{:sign_in=>'login', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'centers/registrations',
                 :sessions=>'centers/sessions'
             }

  devise_for :rhagents,
             :path=>'rhagents',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'rhagents/registrations',
                 :sessions=>'rhagents/sessions'
             }

  resources :users do
    get :matching_offers
    patch :approve
  end
  resources :offers do
    patch :mark_as_filled
  end
  resources :centers
  resources :rhagents
  resources :availabilities
  resources :circonscriptions
  resources :schools
  resources :slots
  resources :diplomas

  # root page of the application

  root 'pages#home'
  get '/animateurs' => 'users#manage'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :center
  belongs_to :school
  has_and_belongs_to_many :diplomas
  has_and_belongs_to_many :slots

  validates :date, presence:true
  validates :slots, presence:true
  validates :diplomas, presence:true
  validates :offer_number, presence:true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all.order(:date).where('date >= ?', DateTime.now.to_date).where('filled = ?', false)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.center = current_center
      if @offer.save
         redirect_to offers_url, notice: "L'Offre a été créée avec succès"
      else
        render :new
      end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    @offer.center = current_center
    if @offer.update(offer_params)
      redirect_to center_path(current_center), notice: "L'Offre a été modifiée avec succès"
    else
      render :edit
    end
  end

  # Mark an offer as filled
  def mark_as_filled
    pending_offer = Offer.find(params[:offer_id])
    pending_offer.update_attribute :filled, params[:filled]
    respond_to do |format|
      if (pending_offer.filled == true)
        format.html { redirect_to center_path(current_center), notice: 'Cette offre a bien été marquée comme pourvue' }
      else
        format.html { redirect_to center_path(current_center), notice: 'Cette offre a bien été remise en ligne' }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Cette offre a bien été suprimée.' }
      format.json { head :no_content }
    end
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:date, :offer_number, :filled, :school_id, :center_id, :diploma_ids => [], :slot_ids => []);
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/edit.html.erb
<div class="container">
  <div class="col-md-8 col-sm-12 col-md-offset-2 form-flex form-panel_wrapper">
      <%= form_for @offer do |f| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="form-heading-title">Modifier l'offre</div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :school_id, 'Ecole', class: 'control-label'%>
              <%= f.collection_select :school_id, current_center.schools, :id, :name, {}, { class: 'form-control' } %>
            </div>
            <div class="form-group">
              <%= f.label :date, 'Date', class: 'control-label'%>
              <%= f.text_field :date, id: 'offer-date', class: 'form-control', placeholder: 'Date', :required => true %>
            </div>
            <div class="form-group required" id="time-slots-choice">
              <%= f.label :slot, 'Plage horaire', class: 'control-label'%>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Choisir une ou plusieurs plages horaires
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <%= f.collection_check_boxes :slot_ids, Slot.all, :id, :name do |b| %>
                      <li class="hide-time-slot">
                        <%= b.check_box %>
                        <%= b.label %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="form-group required">
              <%= f.label :diploma, 'Diplôme requis', class: 'control-label'%>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Choisir un ou plusieurs diplômes
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <%= f.collection_check_boxes :diploma_ids, Diploma.all, :id, :name do |b| %>
                      <li>
                        <%= b.check_box %>
                        <%= b.label %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :offer_number, 'Nombre de postes à pourvoir', class: 'control-label'%>
              <%= f.number_field :offer_number, class: 'form-control', :value => '1' ,:required => true %>
            </div>

          </div> <!-- .panel-body -->
        </div> <!-- .panel -->
        <%= f.submit t('.submit', default: "Modifier l'offre"), class: 'btn btn-edit-form' %>
        <% end %> <!-- form -->
  </div>
</div>

<script>
    $(function(){
        $('#offer-date').datepicker({
            dateFormat: 'yy-mm-dd',
            monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
            dayNamesMin: ['D','L','M','M','J','V','S'],
            minDate: 0,
            beforeShowDay: $.datepicker.noWeekends,
            firstDay: 1
        })
    })
</script>

app/views/offers/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">

    <h2>Toutes les offres de vacation (<%= @offers.count %>)</h2>

    <% @offers.each do |offer| %>

        <div class="offer">
          <div class="offer-school">
            <%= link_to school_path(offer.school) do %>
                <div class="offer-school-name"><%= offer.school.name.titleize %></div>
                <div class="offer-school-address"><%= offer.school.address %></div>
            <% end %>
          </div>
          <div class="offer-content">
            <div class="offer-content-date">
              <i class="fa fa-calendar-o"></i> <%= l offer.date.to_date, format: '%A' %> <%= l offer.date.to_date, format: :long %>
            </div>
            <% offer.slots.each do |slot|  %>
              <div class="offer-content-timeslot badge tealish">
                  <i class="fa fa-clock-o fa-lg"></i> <%= slot.name %>
                </div>
            <% end %>
            <% if offer.date.to_date == DateTime.now.to_date %>
                <div class="offer-content-urgent badge urgent">
                  <i class="fa fa-exclamation fa-lg"></i> Urgent
                </div>
            <% end %>
            <div class="offer-tags">
              <% offer.diplomas.each do |diploma|  %>
                  <div class="offer-tags-diploma <%= diploma.name != "Aucun diplôme" ? "badge butterscotch" : "badge" %>">
                    <i class="fa fa-graduation-cap fa-lg"></i><%= diploma.name %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <div class="col-md-8 col-sm-12 col-md-offset-2 form-flex form-panel_wrapper">
      <%= form_for @offer do |f| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="form-heading-title">Créer une nouvelle offre de vacation animateur</div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :school_id, 'Ecole', class: 'control-label'%>
              <%= f.collection_select :school_id, current_center.schools, :id, :name, {}, { class: 'form-control' } %>
            </div>
            <div class="form-group">
              <%= f.label :date, 'Date', class: 'control-label'%>
              <%= f.text_field :date, id: 'offer-date', class: 'form-control', placeholder: 'Date', :required => true %>
            </div>
            <div class="form-group required" id="time-slots-choice">
              <%= f.label :slot, 'Plage horaire', class: 'control-label'%>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Choisir une ou plusieurs plages horaires
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <div class="date-choice-warning">Choisir d'abord une date</div>
                  <button type="button" id="check_all" class="btn btn-small btn-pink"><%="Toute la journée"%></button>
                  <%= f.collection_check_boxes :slot_ids, Slot.all, :id, :name do |b| %>
                      <li class="hide-time-slot">
                        <%= b.check_box %>
                        <%= b.label %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="form-group required">
              <%= f.label :diploma, 'Diplôme requis', class: 'control-label'%>
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Choisir un ou plusieurs diplômes
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <%= f.collection_check_boxes :diploma_ids, Diploma.all, :id, :name do |b| %>
                      <li class="show-diploma">
                        <%= b.check_box %>
                        <%= b.label %>
                      </li>
                    <% end %>
                  </ul>
                </div>
            </div>
            <div class="form-group">
              <%= f.label :offer_number, 'Nombre de postes à pourvoir', class: 'control-label'%>
              <%= f.number_field :offer_number, class: 'form-control', :value => '1' ,:required => true %>
            </div>

      </div> <!-- .panel-body -->
    </div> <!-- .panel -->
          <%= f.submit t('.submit', default: "Créer l'offre"), class: 'btn btn-edit-form' %>
      <% end %> <!-- form -->
  </div>
</div>

<script>
    $(function(){

        // IE "closest" polyfill
        if (!Element.prototype.matches)
            Element.prototype.matches = Element.prototype.msMatchesSelector ||
                Element.prototype.webkitMatchesSelector;

        if (!Element.prototype.closest)
            Element.prototype.closest = function(s) {
                var el = this;
                if (!document.documentElement.contains(el)) return null;
                do {
                    if (el.matches(s)) return el;
                    el = el.parentElement || el.parentNode;
                } while (el !== null);
                return null;
            };

        if(!$('#offer-date').val()){
            $('#check_all').hide();
        }

        $('#check_all').on("click", function(event){
            // Check all time-slots for one given date
            event.stopPropagation();
            var cbxs = $('.show-time-slot input[type="checkbox"]');
            cbxs.prop("checked", !cbxs.prop("checked"));
        });

        $('input[type="submit"]').on('click', function(e) {
            // Check if at least one of the checboxes is checked before submit
           if (!$('.dropdown-menu .show-time-slot input[type="checkbox"]:checked').length > 0)
           {
               alert('Choisir une plage horaire');
               return false;
           }
           else if (!$('.dropdown-menu .show-diploma input[type="checkbox"]:checked').length > 0)
          {
              alert('Choisir un diplôme');
              return false;
          }
           else {
               return true;
           }

        });

        $('#offer-date').datepicker({
            dateFormat: 'yy-mm-dd',
            monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
            dayNamesMin: ['D','L','M','M','J','V','S'],
            minDate: 0,
            beforeShowDay: $.datepicker.noWeekends,
            firstDay: 1,
            onSelect: function(selected, evnt) {

                var today_time_slot;
                var is_during_holiday = is_holiday(moment(selected));
                var dropdown = $('#time-slots-choice').find('li label');

                $('input[type="checkbox"]').removeAttr('checked');

                $('#check_all').show();
                $('.date-choice-warning').hide();

                for (i=0; i < dropdown.length; i++) {
                    $(dropdown[i].closest('li')).removeClass("hide-time-slot").addClass('show-time-slot');
                }

                if (is_during_holiday) {
                    today_time_slot = TimeSlots.find(function(element) {
                        return element.holiday == true && element.weekday == moment(selected).day();
                    })
                } else {
                    today_time_slot = TimeSlots.find(function(element) {
                        return element.holiday == false  && element.weekday == moment(selected).day();
                    })
                }

                time_slots_checkboxes(today_time_slot);
            }
        });

    function time_slots_checkboxes(day) {
        // Show only time slots that corresponds to the day of the week

        var dropdown = $('#time-slots-choice').find('li label');
        var selected_slots = [];

        day.slots.forEach(function(ts)  {
          selected_slots.push(ts);
        });

        for (i=0; i < dropdown.length; i++) {
            if (selected_slots.indexOf(dropdown[i].innerHTML) == -1) {
                $(dropdown[i].closest('li')).addClass("hide-time-slot").removeClass('show-time-slot');
            }
        }

     }

    })
</script>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>