config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
             :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'users/registrations',
                 :sessions=>'users/sessions'
             }

  devise_for :centers,
             :path=>'recruteur',
             :path_names=>{:sign_in=>'login', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'centers/registrations',
                 :sessions=>'centers/sessions'
             }

  devise_for :rhagents,
             :path=>'rhagents',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{
                 :registrations=>'rhagents/registrations',
                 :sessions=>'rhagents/sessions'
             }

  resources :users do
    get :matching_offers
    patch :approve
  end
  resources :offers do
    patch :mark_as_filled
  end
  resources :centers
  resources :rhagents
  resources :availabilities
  resources :circonscriptions
  resources :schools
  resources :slots
  resources :diplomas

  # root page of the application

  root 'pages#home'
  get '/animateurs' => 'users#manage'
end

app/models/ability.rb
class Ability
  # Defines authorisations for User
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can [:update, :edit, :show, :matching_offers], User, :id => user.id
    cannot :read, Offer
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/models/center.rb
class Center < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,  :confirmable, :recoverable, :rememberable, :trackable, :validatable

  has_many :offers, dependent: :destroy
  has_many :schools

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence:true, length: {maximum: 50}
  validates :last_name, presence:true, length: {maximum: 50}
  validates :phone_number, presence: true, length: {is: 10}, uniqueness: true, numericality: {only_integer: true}
  validates :circonscription, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    end
  end

end

app/models/center_ability.rb
class CenterAbility
  # Defines authorisations for Center
  include CanCan::Ability

  def initialize(center)
    center ||= Center.new # guest user (not logged in)
    can :manage, Offer
    can :read, User
    can :read, School
    can :show, Center, :id => center.id
    cannot :manage, Circonscription
    cannot :manage, Diploma
    cannot :manage, Rhagent
  end
end

app/models/circonscription.rb
class Circonscription < ApplicationRecord
end

app/models/diploma.rb
class Diploma < ApplicationRecord
  has_and_belongs_to_many :offers, dependent: :destroy
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :center
  belongs_to :school
  has_and_belongs_to_many :diplomas
  has_and_belongs_to_many :slots

  validates :date, presence:true
  validates :slots, presence:true
  validates :diplomas, presence:true
  validates :offer_number, presence:true
end

app/models/rhagent.rb
class Rhagent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence:true, length: {maximum: 50}
  validates :last_name, presence:true, length: {maximum: 50}
  validates :circonscription, presence: true

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    end
  end

end

app/models/rhagent_ability.rb
class RhagentAbility
  # Defines authorisations for Rhagent
  include CanCan::Ability

  def initialize(rhagent)
    rhagent ||= Rhagent.new # guest user (not logged in)
    can :read, Offer
    can :read, School
    can :manage, User
    can :show, Rhagent, :id => rhagent.id
    cannot :manage, Circonscription
    cannot :manage, Diploma
    cannot :manage, Center
  end
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :center
  has_many :offer

  validates :name, presence:true
  validates :address, presence:true
  validates :circonscription, presence:true

end

app/models/slot.rb
class Slot < ApplicationRecord
  has_and_belongs_to_many :offers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,  :confirmable, :recoverable, :rememberable, :trackable, :validatable

  has_many :availabilities, dependent: :destroy

  validates :first_name, presence:true, length: {maximum: 50}
  validates :last_name, presence:true, length: {maximum: 50}
  validates :phone_number, presence: true, length: {is: 10}, uniqueness: true, numericality: {only_integer: true}
  validates :birthday, presence: true, on: :update
  validates :soi_number, presence: true, on: :create, uniqueness: true, length: {is: 7}, numericality: { only_integer: true }
  validates :circonscription, presence: true
  validates :diploma, presence: true, on: :update

  has_attached_file :avatar, styles: { medium: "200x200#", thumb: "150x150#" }, default_url: "/assets/profile_default.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      :signed_up_but_unconfirmed
    end
  end

  # Calculate user's age
  def self.age(current_user)
    user_birthdate = current_user.birthday
    user_age = Time.current.year - user_birthdate.year
    return user_age
  end

  # Matching Offers & User availabilities
  def self.offer_matches(current_user)
    user_diploma = current_user.try(:diploma)
    user_availabilities = Availability
                              .joins(:user)
                              .select('date', 'time_slot')
                              .where(user_id: current_user.id)
                              .order(:date)
    offers = Offer.all
             .where('date >= ?', DateTime.now.to_date)
             .where('filled = ?', false)
             .joins(:center)
             .where(centers: {circonscription: current_user.circonscription})


    if offers.exists? && !user_diploma.nil?
      offers_diploma = offers.includes(:diplomas).where(diplomas: {name: user_diploma})

      matches = []

      user_availabilities.each do |user_availability|

        check_conditions = offers_diploma
                     .where(date: user_availability.date)
                     .includes(:slots).where(slots: {name: user_availability.time_slot})

        if !check_conditions.empty?
          check_conditions.each do |match|
              matches.push(match)
          end
        end
      end

    end

    return matches

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    user.avatar.url
  end

end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/diplomas_helper.rb
module DiplomasHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-distributed">
  <div class="footer-left">
    <a href="https://www.paris.fr/actualites/animateur-a-la-ville-de-paris-envoyez-votre-c-v-4459" class="btn btn-pink btn-aaa">Devenir Animateur Périscolaire</a>
    <div class="footer-logo-mairie"><%= image_tag "logo-mairie-de-paris.png"%></div>
    <div class="footer-company-name">AlloAnim © <%= Time.current.year %> avec la DASCO / Ville de Paris</div>
    <%= link_to "Conditions Générales d'Utilisation", asset_path("/cgu_alloanim.pdf"), target: "_blank" %>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-question hidden-sm hidden-xs"></i>
      <p>Une question ? Contactez-nous :</p>
    </div>
    <div>
      <i class="fa fa-envelope hidden-sm hidden-xs"></i>
      <p><a href="mailto:alloanim@futur.paris">alloanim@futur.paris</a></p>
    </div>
  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>A propos d'AlloAnim</span>
      AlloAnim est une <a href="http://missioncapitale.paris.fr/57/horizons/lactu-de-la-ville/lancement-de-start-up-de-ville/" target="_blank">Startup de Ville</a> : un programme expérimental de la Mairie de Paris, porté par des agents de la Ville qui ont identifié sur le terrain une opportunité d’améliorer le service public.
    </p>

    <div class="footer-icons">
      <a href="https://twitter.com/search?f=tweets&vertical=default&q=%23startupdeville&src=typd&lang=fr"><i class="fa fa-twitter"></i></a>

    </div>

  </div>

</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div>
        <% if (user_signed_in? || center_signed_in? || rhagent_signed_in?) %>
          <% if user_signed_in? %>
            <%= link_to 'AlloAnim', user_matching_offers_path(current_user.id),class: 'navbar-brand' %>
          <% end %>
          <% if center_signed_in? || rhagent_signed_in? %>
            <%= link_to 'AlloAnim', users_path ,class: 'navbar-brand' %>
          <% end %>
        <% else %>
          <%= link_to 'AlloAnim', root_path ,class: 'navbar-brand' %>
        <% end %>
        <span class="beta-brand">prototype</span>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <% if center_signed_in? || rhagent_signed_in? %>
         <ul class="nav navbar-nav">
           <% if can? :read, User %>
               <li>
                 <%= link_to users_path, method: :get do %>
                     <i class="fa fa-lg fa-search"></i>
                     Rechercher un animateur
                 <% end %>
               </li>
           <% end %>
         </ul>
    <% end %>

     <ul class="nav navbar-nav navbar-right">
        <% if (user_signed_in? || center_signed_in? || rhagent_signed_in?) %>
            <% if can? :read, Offer %>
                <li><%= link_to "Offres en cours", offers_path, method: :get %>
                </li>
            <% end %>
            <% if user_signed_in? %>
                <li class="menu_link btn btn-turquoise btn-slim nav_action">
                  <%= link_to user_path(current_user, :anchor => "calendar"), method: :get do %>
                      <i class="fa fa-calendar"></i>
                      <span>Remplir mes disponibilités</span>
                  <% end %>
                </li>
                <li class="menu_link">
                  <%= link_to (user_matching_offers_path(current_user.id)) do %>
                    Mes offres
                      <% if @matches.present? %>
                        <span class="badge notification-badge"> <%= @matches.count %></span>
                      <% else %>
                          <span class="badge empty-badge"> <i class="fa fa-info "></i></span>
                      <% end %>
                  <%end %>
                </li>

            <% end %>

        <% end %>
        <% if (!user_signed_in? && !center_signed_in? && !rhagent_signed_in?) %>
           <li class="menu_link_join"><a href="https://api-site-cdn.paris.fr/images/88717" target="_blank">Comment postuler</a> </li>
           <li class="menu-btn btn btn-slim btn-violet"><%= link_to 'Je suis Animateur de Paris', user_session_path, method: :get %></li>
          <li class="menu-btn btn btn-slim btn-pink"><%= link_to 'Je cherche un Animateur', center_session_path, method: :get %></li>
        <% else %>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag avatar_url(current_user), class: 'aaa-img-circle avatar-small' %>
                <% if current_user.first_name.present? && current_user.last_name.present?%>
                    <%= current_user.first_name %> <%= current_user.last_name %>
                    <span class="caret"></span>
                <% end %>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Mon profil', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else if center_signed_in? %>
            <li class="menu_link btn btn-turquoise btn-slim nav_action">
              <%= link_to new_offer_path, method: :get do %>
                  <i class="fa fa-plus"></i>
                    <span>Créer une offre</span>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_center.first_name %> <%= current_center.last_name %> (REV)
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><%= link_to 'Mon Profil', center_path(current_center) %></a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_center_session_path, method: :delete %></li>
              </ul>
            </li>
           <% elsif rhagent_signed_in? %>
             <li class="menu_link btn btn-turquoise btn-slim nav_action">
               <%= link_to animateurs_path, method: :get do %>
                   <i class="fa fa-lg fa-clock-o"></i>
                   Valider les animateurs en attente
               <% end %>
             </li>
             <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                   <%= current_rhagent.first_name %> <%= current_rhagent.last_name %> (Cellule Remplacement)
                   <span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu">
                   <li><a href="#"><%= link_to 'Mon Profil', rhagent_path(current_rhagent) %></a></li>
                   <li role="separator" class="divider"></li>
                   <li><%= link_to 'Déconnexion', destroy_rhagent_session_path, method: :delete %></li>
                 </ul>
               </li>
           <% end %>
        <% end %>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlloAnim</title>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-109230514-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
        window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("1780137113");
    </script>
  </head>

  <body>
    <div class="<%= current_page?(root_path) ? 'home' : 'main-wrapper' %>">
    <% if (user_signed_in? || center_signed_in? ) %>
      <a href="https://goo.gl/forms/H8aAClPBJB7qNRWE3" class="feedback-form hidden-xs" target="_blank">Feedback</a>
    <% end %>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>